version: '2.1'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
    - "4567-4597:4567-4597"
    - "8080:8080"
    environment:
    - SERVICES=s3,sqs,ssm,sns
    - DEFAULT_REGION=eu-central-1
    - DATA_DIR=${DATA_DIR- }
    - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
    - "./localstackdata:/tmp/localstack"
    - "/var/run/docker.sock:/var/run/docker.sock"
  myapp:
    build: ./
    ports:
    - "3000:3000"
    environment:
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
    - AWS_DEFAULT_REGION=eu-central-1
    - LOCALSTACK=true
    - LOCALSTACK_SSM_URL=http://localstack:4583
