apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack-example-app
  labels:
    app.kubernetes.io/name: localstack-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: localstack-example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localstack-example-app
    spec:
      serviceAccountName: localstack-example-e2e
      containers:
        - name: kubernetes-external-secrets
          image: "localstack-example:test"
          imagePullPolicy: IfNotPresent
          env:
          - name: "AWS_ACCESS_KEY_ID"
            value: "foobar"
          - name: "AWS_DEFAULT_REGION"
            value: "eu-central-1"
          - name: "AWS_REGION"
            value: "eu-central-1"
          - name: "AWS_SECRET_ACCESS_KEY"
            value: "foobar"
          - name: "LOCALSTACK"
            value: "true"
          - name: "LOCALSTACK_SSM_URL"
            value: "http://ssm"
